version: "3.8"

services:
  dev:
    shm_size: "3gb"
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    tty: true
    volumes:
      - ../:/workspace/
    working_dir: /workspace/
    command: /bin/bash
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
