version: "3.8"

services:
  dev:
    container_name: advgrads

    build:
      context: ..
      dockerfile: Dockerfile

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

    volumes:
      - ..:/workspace:cached
    working_dir: /workspace

    privileged: true
    shm_size: "12gb"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    tty: true
    stdin_open: true
    command: /bin/bash
